language: python
python:
  - 2.6
  - 2.7
env:
  - PLONE_VERSION=4.0
  - PLONE_VERSION=4.1
  - PLONE_VERSION=4.2
  - PLONE_VERSION=4.3 QA=true
matrix:
  exclude:
    - python: 2.7
      env: PLONE_VERSION=4.0
    - python: 2.7
      env: PLONE_VERSION=4.1
    - python: 2.6
      env: PLONE_VERSION=4.2
    - python: 2.6
      env: PLONE_VERSION=4.3 QA=true
install:
  - sed -ie "s#travis-4.x.cfg#travis-$PLONE_VERSION.x.cfg#" travis.cfg
  - mkdir -p buildout-cache/downloads
  - python bootstrap.py -c travis.cfg
  - bin/buildout -c travis.cfg -N -q -t 3
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script: bin/test
after_success:
  - bin/flake8 --ignore=E501 --max-complexity=12 sc/social/like
  - bin/coverage.sh 87
  - npm install csslint -g 2>/dev/null
  - find sc/social/like -type f -name *.css ! -name jquery\* | xargs csslint
  - npm install jshint -g 2>/dev/null
  - find sc/social/like -type f -name *.js ! -name jquery\* -exec jshint {} ';'
notifications:
  irc: irc.freenode.org#simplesconsultoria
